version: "3.7"

services:
    server:
      restart: always
      build:
        context: ./server
        dockerfile: Dockerfile
      image: intervyou-server
      container_name: intervyou-node-server
      command: /usr/src/app/node_modules/.bin/nodemon server.js
      ports: 
        - "5000:5000"
      depends_on:
        - mongo
      volumes:
        - /app/node_modules
        - ./server:/app
      networks:
        - intervyou-network

    mongo:
      restart: always
      image: mongo
      environment:
        MONGO_INITDB_DATABASE: testdb
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27017:27017"
      volumes:
        - mongodb-data:/data/db
      networks:
        - intervyou-network

    client:
      restart: always
      build:
        context: ./client
        dockerfile: Dockerfile
      image: intervyou-client
      container_name: intervyou-react-client
      command: npm start
      depends_on:
        - server
      ports:
        - "3000:3000"
      volumes:
        - /app/node_modules
        - ./client:/app
      networks:
        - intervyou-network

    nginx:
      image: intervyou-nginx
      depends_on:
        - client
        - server
      restart: always
      build: 
        dockerfile: Dockerfile
        context: ./nginx
      ports:
        - "80:80"
        - "443:443"
      networks:
        - intervyou-network

networks:
  intervyou-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local